# Generated by Django 5.2.3 on 2025-07-01 05:03

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Biker',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(max_length=150)),
                ('phone_number', models.CharField(max_length=15)),
                ('cnic', models.CharField(max_length=15, unique=True)),
                ('password', models.CharField(max_length=128)),
                ('bike_model', models.CharField(max_length=100)),
                ('vehicle_number', models.CharField(max_length=50)),
                ('current_request_id', models.IntegerField(blank=True, null=True)),
                ('joined_at', models.DateTimeField(default=django.utils.timezone.now)),
            ],
        ),
    ]
