# Generated by Django 5.2.3 on 2025-07-01 05:16

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Biker_app', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='BikerAvailability',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_available', models.BooleanField(default=True)),
                ('location_lat', models.FloatField()),
                ('location_lng', models.FloatField()),
                ('updated_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('biker', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='availability', to='Biker_app.biker')),
            ],
        ),
    ]
