# Generated by Django 5.2.3 on 2025-07-01 05:27

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Biker_app', '0002_bikeravailability'),
    ]

    operations = [
        migrations.CreateModel(
            name='Earnings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('daily_earning', models.FloatField(default=0)),
                ('weekly_earning', models.FloatField(default=0)),
                ('monthly_earning', models.FloatField(default=0)),
                ('total_rides', models.PositiveIntegerField(default=0)),
                ('acceptance_rate', models.FloatField(default=0)),
                ('rating', models.FloatField(default=0)),
                ('biker', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='earnings', to='Biker_app.biker')),
            ],
        ),
    ]
