# Generated by Django 5.2.3 on 2025-07-01 04:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users_app', '0004_bikerapplication'),
    ]

    operations = [
        migrations.AddField(
            model_name='bikerapplication',
            name='bikeModel',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='bikerapplication',
            name='vehicleNumber',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
