# Generated by Django 5.2.3 on 2025-07-04 06:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core_app', '0005_history'),
    ]

    operations = [
        migrations.AddField(
            model_name='ride',
            name='distance_km',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
