# Generated by Django 5.2.3 on 2025-07-06 15:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core_app', '0006_ride_distance_km'),
    ]

    operations = [
        migrations.CreateModel(
            name='price_info',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('price_id', models.CharField(max_length=100)),
                ('pickup_location', models.CharField(max_length=250)),
                ('dropoff_location', models.CharField(max_length=250)),
                ('price', models.CharField(max_length=250)),
            ],
        ),
    ]
