# Generated by Django 5.2.3 on 2025-07-06 15:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core_app', '0007_price_info'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='ride',
            name='distance_km',
        ),
    ]
